### ISSUE TITLE
LiteFS folder mappings explained

### ISSUE THREAD

**Issue by gerhardcit** [superfly/docs#1429]
On this page
https://fly.io/docs/litefs/speedrun/

could to explain the relationship between `fly.toml`
```
[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
```

**and** `litefs.yml`
```
fuse:
  dir: "/litefs"

data:
  dir: "/var/lib/litefs"
```

**and** the Docker file (created by https://github.com/fly-apps/node-demo)
```
# Setup sqlite3 on a separate volume
RUN mkdir -p /data
VOLUME /data

ENV DATABASE_URL="file:///data/my.db"
ENTRYPOINT litefs mount
```

How should those be aligned?
