### ISSUE TITLE
Issue with the "Fly Launch configuration (fly.toml)" doc

### ISSUE THREAD

**Issue by fliepeltje** [superfly/docs#1662]
I found an issue with this document.

Title: Fly Launch configuration (fly.toml)
Location: https://fly.io/docs/reference/configuration/
Source: https://github.com/superfly/docs/blob/main/reference/configuration.html.markerb

### Describe the issue

The gpu kind is incorrect in the [vm section](https://fly.io/docs/reference/configuration/#the-vm-section); this concerns the code block.

It should be this instead:

```toml
[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
  cpus = 4
  cpu_kind = "performance"
  gpus = 1
  gpu_kind = "a100-40gb"
  kernel_args = "no-hlt=true"
  host_dedication_id = "customer-id"
  processes = ["app"]
```
