### ISSUE TITLE
Invalid .yml in app-guides/continuous-deployment-with-github-actions.md

### ISSUE THREAD

**Issue by gworkman** [superfly/docs#574]
The GitHub Actions continuous deployment guide seems to contain invalid indentation for .yml file. I don't know that much about the format, so it tripped me up a bit while trying to setup my CD pipeline. The contents seem correct in the GitHub-rendered file though, so it might be a styling issue on the website.

See reference image below:

<img width="738" alt="Screen Shot 2023-02-05 at 10 15 31 PM" src="https://user-images.githubusercontent.com/15219790/216876078-1b1f398e-0698-46a3-855e-8bb9e2410c39.png">

Expected output:

```yaml
name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
 ```
